# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/progs/sc2/scom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/progs/sc2/scom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/progs/sc2/scom/CMakeFiles /home/pi/progs/sc2/scom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/progs/sc2/scom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mtbus

# Build rule for target.
mtbus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mtbus
.PHONY : mtbus

# fast build rule for target.
mtbus/fast:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/build
.PHONY : mtbus/fast

src/CHS.o: src/CHS.c.o
.PHONY : src/CHS.o

# target to build an object file
src/CHS.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/CHS.c.o
.PHONY : src/CHS.c.o

src/CHS.i: src/CHS.c.i
.PHONY : src/CHS.i

# target to preprocess a source file
src/CHS.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/CHS.c.i
.PHONY : src/CHS.c.i

src/CHS.s: src/CHS.c.s
.PHONY : src/CHS.s

# target to generate assembly for a file
src/CHS.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/CHS.c.s
.PHONY : src/CHS.c.s

src/MTBus.o: src/MTBus.c.o
.PHONY : src/MTBus.o

# target to build an object file
src/MTBus.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBus.c.o
.PHONY : src/MTBus.c.o

src/MTBus.i: src/MTBus.c.i
.PHONY : src/MTBus.i

# target to preprocess a source file
src/MTBus.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBus.c.i
.PHONY : src/MTBus.c.i

src/MTBus.s: src/MTBus.c.s
.PHONY : src/MTBus.s

# target to generate assembly for a file
src/MTBus.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBus.c.s
.PHONY : src/MTBus.c.s

src/MTBusConfiguration.o: src/MTBusConfiguration.c.o
.PHONY : src/MTBusConfiguration.o

# target to build an object file
src/MTBusConfiguration.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusConfiguration.c.o
.PHONY : src/MTBusConfiguration.c.o

src/MTBusConfiguration.i: src/MTBusConfiguration.c.i
.PHONY : src/MTBusConfiguration.i

# target to preprocess a source file
src/MTBusConfiguration.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusConfiguration.c.i
.PHONY : src/MTBusConfiguration.c.i

src/MTBusConfiguration.s: src/MTBusConfiguration.c.s
.PHONY : src/MTBusConfiguration.s

# target to generate assembly for a file
src/MTBusConfiguration.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusConfiguration.c.s
.PHONY : src/MTBusConfiguration.c.s

src/MTBusManager.o: src/MTBusManager.c.o
.PHONY : src/MTBusManager.o

# target to build an object file
src/MTBusManager.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusManager.c.o
.PHONY : src/MTBusManager.c.o

src/MTBusManager.i: src/MTBusManager.c.i
.PHONY : src/MTBusManager.i

# target to preprocess a source file
src/MTBusManager.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusManager.c.i
.PHONY : src/MTBusManager.c.i

src/MTBusManager.s: src/MTBusManager.c.s
.PHONY : src/MTBusManager.s

# target to generate assembly for a file
src/MTBusManager.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusManager.c.s
.PHONY : src/MTBusManager.c.s

src/MTBusRoutingTable.o: src/MTBusRoutingTable.c.o
.PHONY : src/MTBusRoutingTable.o

# target to build an object file
src/MTBusRoutingTable.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusRoutingTable.c.o
.PHONY : src/MTBusRoutingTable.c.o

src/MTBusRoutingTable.i: src/MTBusRoutingTable.c.i
.PHONY : src/MTBusRoutingTable.i

# target to preprocess a source file
src/MTBusRoutingTable.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusRoutingTable.c.i
.PHONY : src/MTBusRoutingTable.c.i

src/MTBusRoutingTable.s: src/MTBusRoutingTable.c.s
.PHONY : src/MTBusRoutingTable.s

# target to generate assembly for a file
src/MTBusRoutingTable.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTBusRoutingTable.c.s
.PHONY : src/MTBusRoutingTable.c.s

src/MTbusServer.o: src/MTbusServer.c.o
.PHONY : src/MTbusServer.o

# target to build an object file
src/MTbusServer.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTbusServer.c.o
.PHONY : src/MTbusServer.c.o

src/MTbusServer.i: src/MTbusServer.c.i
.PHONY : src/MTbusServer.i

# target to preprocess a source file
src/MTbusServer.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTbusServer.c.i
.PHONY : src/MTbusServer.c.i

src/MTbusServer.s: src/MTbusServer.c.s
.PHONY : src/MTbusServer.s

# target to generate assembly for a file
src/MTbusServer.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/MTbusServer.c.s
.PHONY : src/MTbusServer.c.s

src/NetVarAccesManager.o: src/NetVarAccesManager.c.o
.PHONY : src/NetVarAccesManager.o

# target to build an object file
src/NetVarAccesManager.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/NetVarAccesManager.c.o
.PHONY : src/NetVarAccesManager.c.o

src/NetVarAccesManager.i: src/NetVarAccesManager.c.i
.PHONY : src/NetVarAccesManager.i

# target to preprocess a source file
src/NetVarAccesManager.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/NetVarAccesManager.c.i
.PHONY : src/NetVarAccesManager.c.i

src/NetVarAccesManager.s: src/NetVarAccesManager.c.s
.PHONY : src/NetVarAccesManager.s

# target to generate assembly for a file
src/NetVarAccesManager.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/NetVarAccesManager.c.s
.PHONY : src/NetVarAccesManager.c.s

src/TBusManager.o: src/TBusManager.c.o
.PHONY : src/TBusManager.o

# target to build an object file
src/TBusManager.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/TBusManager.c.o
.PHONY : src/TBusManager.c.o

src/TBusManager.i: src/TBusManager.c.i
.PHONY : src/TBusManager.i

# target to preprocess a source file
src/TBusManager.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/TBusManager.c.i
.PHONY : src/TBusManager.c.i

src/TBusManager.s: src/TBusManager.c.s
.PHONY : src/TBusManager.s

# target to generate assembly for a file
src/TBusManager.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/TBusManager.c.s
.PHONY : src/TBusManager.c.s

src/Terabus.o: src/Terabus.c.o
.PHONY : src/Terabus.o

# target to build an object file
src/Terabus.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/Terabus.c.o
.PHONY : src/Terabus.c.o

src/Terabus.i: src/Terabus.c.i
.PHONY : src/Terabus.i

# target to preprocess a source file
src/Terabus.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/Terabus.c.i
.PHONY : src/Terabus.c.i

src/Terabus.s: src/Terabus.c.s
.PHONY : src/Terabus.s

# target to generate assembly for a file
src/Terabus.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/Terabus.c.s
.PHONY : src/Terabus.c.s

src/UartDriver.o: src/UartDriver.c.o
.PHONY : src/UartDriver.o

# target to build an object file
src/UartDriver.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/UartDriver.c.o
.PHONY : src/UartDriver.c.o

src/UartDriver.i: src/UartDriver.c.i
.PHONY : src/UartDriver.i

# target to preprocess a source file
src/UartDriver.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/UartDriver.c.i
.PHONY : src/UartDriver.c.i

src/UartDriver.s: src/UartDriver.c.s
.PHONY : src/UartDriver.s

# target to generate assembly for a file
src/UartDriver.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/UartDriver.c.s
.PHONY : src/UartDriver.c.s

src/UartManager.o: src/UartManager.c.o
.PHONY : src/UartManager.o

# target to build an object file
src/UartManager.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/UartManager.c.o
.PHONY : src/UartManager.c.o

src/UartManager.i: src/UartManager.c.i
.PHONY : src/UartManager.i

# target to preprocess a source file
src/UartManager.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/UartManager.c.i
.PHONY : src/UartManager.c.i

src/UartManager.s: src/UartManager.c.s
.PHONY : src/UartManager.s

# target to generate assembly for a file
src/UartManager.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/UartManager.c.s
.PHONY : src/UartManager.c.s

src/archive.o: src/archive.c.o
.PHONY : src/archive.o

# target to build an object file
src/archive.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/archive.c.o
.PHONY : src/archive.c.o

src/archive.i: src/archive.c.i
.PHONY : src/archive.i

# target to preprocess a source file
src/archive.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/archive.c.i
.PHONY : src/archive.c.i

src/archive.s: src/archive.c.s
.PHONY : src/archive.s

# target to generate assembly for a file
src/archive.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/archive.c.s
.PHONY : src/archive.c.s

src/connect.o: src/connect.c.o
.PHONY : src/connect.o

# target to build an object file
src/connect.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/connect.c.o
.PHONY : src/connect.c.o

src/connect.i: src/connect.c.i
.PHONY : src/connect.i

# target to preprocess a source file
src/connect.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/connect.c.i
.PHONY : src/connect.c.i

src/connect.s: src/connect.c.s
.PHONY : src/connect.s

# target to generate assembly for a file
src/connect.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/connect.c.s
.PHONY : src/connect.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/main.c.s
.PHONY : src/main.c.s

src/netdev.o: src/netdev.c.o
.PHONY : src/netdev.o

# target to build an object file
src/netdev.c.o:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/netdev.c.o
.PHONY : src/netdev.c.o

src/netdev.i: src/netdev.c.i
.PHONY : src/netdev.i

# target to preprocess a source file
src/netdev.c.i:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/netdev.c.i
.PHONY : src/netdev.c.i

src/netdev.s: src/netdev.c.s
.PHONY : src/netdev.s

# target to generate assembly for a file
src/netdev.c.s:
	$(MAKE) -f CMakeFiles/mtbus.dir/build.make CMakeFiles/mtbus.dir/src/netdev.c.s
.PHONY : src/netdev.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mtbus"
	@echo "... rebuild_cache"
	@echo "... src/CHS.o"
	@echo "... src/CHS.i"
	@echo "... src/CHS.s"
	@echo "... src/MTBus.o"
	@echo "... src/MTBus.i"
	@echo "... src/MTBus.s"
	@echo "... src/MTBusConfiguration.o"
	@echo "... src/MTBusConfiguration.i"
	@echo "... src/MTBusConfiguration.s"
	@echo "... src/MTBusManager.o"
	@echo "... src/MTBusManager.i"
	@echo "... src/MTBusManager.s"
	@echo "... src/MTBusRoutingTable.o"
	@echo "... src/MTBusRoutingTable.i"
	@echo "... src/MTBusRoutingTable.s"
	@echo "... src/MTbusServer.o"
	@echo "... src/MTbusServer.i"
	@echo "... src/MTbusServer.s"
	@echo "... src/NetVarAccesManager.o"
	@echo "... src/NetVarAccesManager.i"
	@echo "... src/NetVarAccesManager.s"
	@echo "... src/TBusManager.o"
	@echo "... src/TBusManager.i"
	@echo "... src/TBusManager.s"
	@echo "... src/Terabus.o"
	@echo "... src/Terabus.i"
	@echo "... src/Terabus.s"
	@echo "... src/UartDriver.o"
	@echo "... src/UartDriver.i"
	@echo "... src/UartDriver.s"
	@echo "... src/UartManager.o"
	@echo "... src/UartManager.i"
	@echo "... src/UartManager.s"
	@echo "... src/archive.o"
	@echo "... src/archive.i"
	@echo "... src/archive.s"
	@echo "... src/connect.o"
	@echo "... src/connect.i"
	@echo "... src/connect.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/netdev.o"
	@echo "... src/netdev.i"
	@echo "... src/netdev.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

